Repository sonjek/mouse-stay-up, pull requests merged in 2024-04, with the labels that each got.

#4 chore: Cleanup
  .DS_Store
  .gitignore
  internal/mouse/mouse.go
Labels: kind/refactor

#5 feat: Change default wait time from static 10 sec to dynamic 10-60 sec
  internal/mouse/mouse.go
  internal/tray/tray.go
Labels: kind/feature

#6 feat: Remove 10 sec and 20 sec intervals
  internal/tray/tray.go
Labels: kind/feature

#7 feat: Change max movement distance to 8px
  internal/mouse/mouse.go
Labels: kind/feature

#8 feat: Panic for unsupported unsupported in OpenWebPage
  .gitignore
  internal/utils/about.go
Labels: kind/feature

#9 feat: Disable/Enable Sleep Interval block on Disable/Enable app
  internal/tray/tray.go
Labels: kind/feature

#10 feat: Add make clean/install/uninstall
  Makefile
  README.md
  internal/.DS_Store
  internal/tray/.DS_Store
Labels: kind/feature

#11 feat: Rename Sleep Interval to Check Interval
  internal/tray/tray.go
Labels: kind/feature

#12 refactor: Fix wrong name of utils
  internal/utils/utils.go
Labels: kind/refactor

#13 refactor: Move sleep before check
  internal/mouse/mouse.go
Labels: kind/refactor

#14 refactor: Create Config and use in Tray and Mouse
  cmd/app/main.go
  internal/config/config.go
  internal/mouse/mouse.go
  internal/tray/tray.go
Labels: kind/refactor

#16 feat: Remove custom Sleep Interval selection
  internal/config/config.go
  internal/mouse/mouse.go
  internal/tray/tray.go
Labels: kind/feature

#17 docs: Update README.md
  README.md
Labels: kind/docs

#18 ci: Rename build.yml to ci.yml
  .github/workflows/ci.yml
Labels: kind/ci

#20 refactor: Handle error in utils.OpenWebPage()
  internal/tray/tray.go
  internal/utils/utils.go
Labels: kind/refactor

#19 ci: Add lint job to ci.yml
  .github/workflows/ci.yml
Labels: kind/ci

#22 chore: Add .github/FUNDING.yml
  .github/FUNDING.yml
Labels: kind/chore

#23 Lint
  .golangci.yml
  cmd/app/main.go
  internal/mouse/mouse.go
  internal/tray/tray.go
  internal/utils/utils.go
Labels: kind/chore

#24 ci: Add skip-cache: true for golangci/golangci-lint-action
  .github/workflows/ci.yml
Labels: kind/ci

#25 docs: Add badges to README.md
  README.md
Labels: kind/docs, kind/ci

#26 ci: Add timeout 10m for golangci/golangci-lint-action
  .github/workflows/ci.yml
Labels: kind/ci

#27 ci: Execute CI tasks according to modifications
  .github/workflows/ci.yml
  .github/workflows/files-changed.yml
Labels: kind/ci

#28 chore: Add .github/dependabot.yml
  .github/dependabot.yml
Labels: kind/chore

#30 feat: Bump Go Modules
  go.mod
  go.sum
Labels: kind/feature

#29 feat: Dynamic shift of working hours don't exceed end time or precede start time
  Makefile
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: kind/feature

#31 ci: Add GitHub Actions for test
  .github/workflows/ci.yml
Labels: kind/ci

#32 chore: Add more makefile tools
  Makefile
  README.md
Labels: kind/chore

#33 ci: Run lint only if code or lint rules or ci actions have changed
  .github/workflows/ci.yml
  .github/workflows/files-changed.yml
Labels: kind/ci

#35 refactor: Don't change activity state directly
  internal/config/config.go
  internal/tray/tray.go
Labels: kind/refactor

#36 feat: Restore previous settings after restarting program
  go.mod
  go.sum
  internal/config/config.go
  internal/tray/tray.go
  pkg/config/config.go
Labels: kind/feature

#37 refactor: Code cleanup
  internal/tray/tray.go
Labels: kind/refactor

#38 refactor: Bump go-vgo/robotgo
  go.mod
  go.sum
Labels: kind/refactor
